'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import type {HomeContent,Product} from '../../lib/api';

type Lead={id:string;reference:string;name:string;email:string;country:string;type:string;subject:string;message:string;status:string;internal_note:string;version:number;created_at:string};
type Audit={id:string;email:string;action:string;entity:string;entity_id:string;created_at:string};
type FormProduct=Omit<Product,'image_alt'>&{image_alt?:string|null};
const blank:FormProduct={id:'',slug:'',name:'',sku:'',summary:'',description:'',category:'Bowling',age_min:3,age_max:12,environment:'indoor',features:[],specs:{},safety_notes:'',image_id:null,status:'draft',seo_title:'',seo_description:'',version:1};
class RequestError extends Error {constructor(message:string,public fields:Record<string,string>={}){super(message);}}
async function request<T>(path:string,body?:unknown,method='POST'):Promise<T>{
 const response=await fetch(`/api/${path}`,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json','x-wm-csrf':'1'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await response.json();if(response.status===401){window.location.href='/admin/login';throw new RequestError('Please sign in.');}
 if(!response.ok)throw new RequestError(data.message||'Request failed.',data.field_errors||{});return data;
}
export default function Admin(){
 const [user,setUser]=useState(''),[tab,setTab]=useState('Products'),[products,setProducts]=useState<Product[]>([]),[leads,setLeads]=useState<Lead[]>([]),[audit,setAudit]=useState<Audit[]>([]),[home,setHome]=useState<HomeContent|null>(null);
 const [editing,setEditing]=useState<FormProduct|null>(null),[selected,setSelected]=useState<Lead|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string>>({});
 const errorRef=useRef<HTMLDivElement>(null);
 function failure(e:unknown){setError(e instanceof Error?e.message:'Please try again.');setFields(e instanceof RequestError?e.fields:{});setTimeout(()=>errorRef.current?.focus(),0);}
 async function refresh(){const[p,l,h,a]=await Promise.all([request<Product[]>('admin/products'),request<Lead[]>('admin/leads'),request<HomeContent>('content/home'),request<Audit[]>('admin/audit')]);setProducts(p);setLeads(l);setHome(h);setAudit(a);}
 useEffect(()=>{request<{email:string}>('auth/me').then(async me=>{setUser(me.email);await refresh();}).catch(failure).finally(()=>setLoading(false));},[]);
 function selectTab(value:string){setTab(value);setEditing(null);setSelected(null);setError('');setMessage('');}
 async function saveProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError('');setFields({});
  const fd=new FormData(e.currentTarget);const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement;
  const payload={...editing,name:String(fd.get('name')),slug:String(fd.get('slug')),sku:String(fd.get('sku')),summary:String(fd.get('summary')),description:String(fd.get('description')),category:String(fd.get('category')),age_min:Number(fd.get('age_min')),age_max:Number(fd.get('age_max')),environment:String(fd.get('environment')),features:String(fd.get('features')).split('\n').map(v=>v.trim()).filter(Boolean),safety_notes:String(fd.get('safety_notes')),seo_title:String(fd.get('seo_title')),seo_description:String(fd.get('seo_description')),status:submitter?.value||'draft',specs:{} as Record<string,string>};
  for(const line of String(fd.get('specs')).split('\n').filter(v=>v.trim())){const i=line.indexOf(':');if(i<1){setBusy(false);failure(new Error('Write each specification as Name: value.'));return;}payload.specs[line.slice(0,i).trim()]=line.slice(i+1).trim();}
  try{const saved=await request<Product>(editing.id?`admin/products/${editing.id}`:'admin/products',payload,editing.id?'PATCH':'POST');setEditing(saved);await refresh();setMessage(saved.status==='active'?'Product published. It is now visible on the website.':saved.status==='archived'?'Product archived. Its detail URL is retained.':'Draft saved.');}catch(e){failure(e);}finally{setBusy(false);}
 }
 async function upload(file?:File){if(!file||!editing)return;setBusy(true);setError('');
  try{if(file.size>2*1024*1024)throw new Error('Choose an image under 2 MB.');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const saved=await request<{id:string;alt:string}>('admin/media',{data,alt:editing.name||file.name.replace(/\.[^.]+$/,'')});setEditing({...editing,image_id:saved.id,image_alt:saved.alt});setMessage('Image uploaded. Save the product to attach it.');}catch(e){failure(e);}finally{setBusy(false);}
 }
 async function saveLead(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const saved=await request<Lead>(`admin/leads/${selected.id}`,{status:fd.get('status'),internal_note:fd.get('internal_note'),version:selected.version},'PATCH');setSelected(saved);await refresh();setMessage('Inquiry updated.');}catch(e){failure(e);}finally{setBusy(false);}}
 async function saveHome(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!home)return;setBusy(true);setError('');try{await request('admin/content/home',{...Object.fromEntries(new FormData(e.currentTarget)),version:home.version},'PATCH');await refresh();setMessage('Homepage content updated.');}catch(e){failure(e);}finally{setBusy(false);}}
 const field=(name:string,label:string,large=false)=>{const value=editing?(editing as any)[name]:'';return <label key={name}>{label}{large?<textarea id={name} name={name} rows={name==='description'?6:3} defaultValue={value} aria-describedby={`${name}-error`}/>:<input id={name} name={name} defaultValue={value} required={['name','sku','slug'].includes(name)} aria-describedby={`${name}-error`}/>}<small className="field-error" id={`${name}-error`}>{fields[name]}</small></label>;};
 return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="wordmark">WEMOVE<span>TEAM WORKSPACE</span></Link><nav aria-label="Workspace">{['Products','Inquiries','Homepage','Activity'].map(t=><button key={t} onClick={()=>selectTab(t)} aria-current={tab===t?'page':undefined}>{t}{t==='Inquiries'&&<span>{leads.filter(l=>l.status==='new').length}</span>}</button>)}</nav><div className="sidebar-bottom"><Link href="/" target="_blank">View website ↗</Link><small>{user}</small><button onClick={async()=>{await request('auth/logout',{});window.location.href='/admin/login';}}>Sign out</button></div></aside>
 <main className="admin-main" id="main-content"><header className="admin-heading"><div><p className="eyebrow">CONTENT & OPERATIONS</p><h1>{editing?(editing.id?'Edit product':'New product'):selected?selected.reference:tab}</h1></div>{tab==='Products'&&!editing&&<button className="button" onClick={()=>{setEditing({...blank});setMessage('');setError('');}}>+ New product</button>}</header>
 {error&&<div ref={errorRef} className="error-summary" role="alert" tabIndex={-1}><strong>{error}</strong>{Object.entries(fields).map(([key,val])=><a href={`#${key.split('.')[0]}`} key={key}>{key}: {val}</a>)}</div>}{message&&<div className="success-message" role="status">{message}</div>}
 {loading?<p role="status">Loading workspace…</p>:<>
 {tab==='Products'&&!editing&&<><div className="admin-summary"><span><b>{products.length}</b>Total products</span><span><b>{products.filter(p=>p.status==='active').length}</b>Published</span><span><b>{products.filter(p=>p.status==='draft').length}</b>Drafts</span></div>{products.length?<div className="table-scroll"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Status</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>/{p.slug}</small></td><td>{p.sku}</td><td>{p.category}</td><td><span className={`badge ${p.status}`}>{p.status}</span></td><td><button className="text-button" onClick={()=>{setEditing(p);setMessage('');}}>Edit <span className="sr-only">{p.name}</span> ↗</button></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>Your collection starts here.</h2><p>Create a draft, add real product information and an image, then publish.</p></div>}</>}
 {tab==='Products'&&editing&&<form className="editor" key={`${editing.id}:${editing.version}`} onSubmit={saveProduct}><button className="text-button" type="button" onClick={()=>setEditing(null)}>← Back to products</button><div className="editor-grid"><section><h2>Product information</h2><div className="form-columns">{field('name','Product name')}{field('sku','SKU')}{field('slug','URL slug')}<label>Activity<select name="category" defaultValue={editing.category}>{['Bowling','Balance & coordination','Outdoor games'].map(v=><option key={v}>{v}</option>)}</select></label></div>{field('summary','Short description',true)}{field('description','Description / how to play',true)}<label>Features <small>One per line. Three to six are required to publish.</small><textarea id="features" name="features" rows={4} defaultValue={editing.features.join('\n')}/></label><div className="form-columns"><label>Minimum age<input type="number" name="age_min" id="age_min" min="0" max="99" defaultValue={editing.age_min}/></label><label>Maximum age<input type="number" name="age_max" id="age_max" min="0" max="99" defaultValue={editing.age_max}/></label><label>Play space<select name="environment" defaultValue={editing.environment}><option value="indoor">Indoor</option><option value="outdoor">Outdoor</option><option value="both">Both</option></select></label></div><label>Specifications <small>One per line, for example Material: wood. Enter verified details only.</small><textarea name="specs" rows={4} defaultValue={Object.entries(editing.specs).map(([k,v])=>`${k}: ${v}`).join('\n')}/></label>{field('safety_notes','Safety & care',true)}</section>
 <section><h2>Main image</h2><div className="upload-box" id="image_id">{editing.image_id?<img src={`/api/media/${editing.image_id}`} alt={editing.image_alt||'Product preview'} width="320" height="320"/>:<p>Upload a real product image.</p>}<label>Choose image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label><small>PNG, JPEG or WebP · up to 2 MB</small><small className="field-error">{fields.image_id}</small></div><h2>Search appearance</h2>{field('seo_title','SEO title')}{field('seo_description','SEO description',true)}<p className="notice">Drafts stay private. Published products appear immediately. Archived products keep their detail URL.</p></section></div><div className="editor-actions"><button className="button secondary" value="draft" disabled={busy}>{busy?'Saving…':'Save draft'}</button><button className="button" value="active" disabled={busy}>Publish product</button>{editing.id&&<button className="text-button danger" value="archived" disabled={busy}>Archive</button>}</div></form>}
 {tab==='Inquiries'&&!selected&&(leads.length?<div className="table-scroll"><table><thead><tr><th>Reference / subject</th><th>Contact</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><strong>{l.subject}</strong><small>{l.reference}</small></td><td>{l.name}<small>{l.email}</small></td><td>{l.type}</td><td><span className="badge">{l.status.replace('_',' ')}</span></td><td><button className="text-button" onClick={()=>{setSelected(l);setMessage('');}}>Open ↗</button></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>No inquiries yet.</h2><p>Messages submitted through the contact page will appear here.</p><Link href="/contact" className="text-link">Open contact page ↗</Link></div>)}
 {tab==='Inquiries'&&selected&&<div className="editor"><button className="text-button" onClick={()=>setSelected(null)}>← All inquiries</button><div className="editor-grid"><section><p className="eyebrow">{selected.type}</p><h2>{selected.subject}</h2><p>{selected.name} · {selected.email} · {selected.country}</p><p className="preserve-text inquiry-message">{selected.message}</p></section><form onSubmit={saveLead} key={selected.version}><label>Status<select name="status" defaultValue={selected.status}><option value="new">New</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></label><label>Internal note<textarea name="internal_note" rows={7} maxLength={4000} defaultValue={selected.internal_note}/><small>Only visible in this workspace. Saving does not send an email.</small></label><button className="button" disabled={busy}>{busy?'Saving…':'Save changes'}</button></form></div></div>}
 {tab==='Homepage'&&home&&<form className="editor home-editor" key={home.version} onSubmit={saveHome}><h2>Brand introduction</h2><p>Update the live homepage and Our story page.</p>{Object.entries({hero_title:'Hero title',hero_subtitle:'Hero subtitle',cta_label:'Product button label',about:'Brand introduction'}).map(([name,label])=><label key={name}>{label}{name==='about'?<textarea name={name} rows={8} defaultValue={(home.data as any)[name]} required/>:<input name={name} defaultValue={(home.data as any)[name]} required/>}</label>)}<button className="button" disabled={busy}>{busy?'Saving…':'Save website content'}</button></form>}
 {tab==='Activity'&&<div className="table-scroll"><table><thead><tr><th>Action</th><th>Object</th><th>Team member</th><th>Time</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{a.action}</td><td>{a.entity}<small>{a.entity_id}</small></td><td>{a.email||'System'}</td><td>{new Date(a.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}
 </> }</main></div>;
}
