'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import type {HomeContent,Product} from '../../lib/api';
import {LanguageSwitcher,useLocale} from '../../components/language-provider';
import {displayCategory,displayEnvironment,localizeApiMessage,pick} from '../../lib/i18n';

type Lead={id:string;reference:string;name:string;email:string;country:string;type:string;subject:string;message:string;status:string;internal_note:string;version:number;created_at:string};
type Audit={id:string;email:string;action:string;entity:string;entity_id:string;created_at:string};
type FormProduct=Omit<Product,'image_alt'>&{image_alt?:string|null};
const blank:FormProduct={id:'',slug:'',name:'',sku:'',summary:'',description:'',category:'Bowling',age_min:3,age_max:12,environment:'indoor',features:[],specs:{},safety_notes:'',image_id:null,status:'draft',seo_title:'',seo_description:'',version:1};
class RequestError extends Error {constructor(message:string,public fields:Record<string,string>={}){super(message);}}
async function request<T>(path:string,body?:unknown,method='POST'):Promise<T>{
 const response=await fetch(`/api/${path}`,{method:body===undefined?'GET':method,headers:body===undefined?{}:{'Content-Type':'application/json','x-wm-csrf':'1'},body:body===undefined?undefined:JSON.stringify(body)});
 const data=await response.json();if(response.status===401){window.location.href='/admin/login';throw new RequestError('Please sign in.');}
 if(!response.ok)throw new RequestError(data.message||'Request failed.',data.field_errors||{});return data;
}
export default function Admin(){
 const{locale}=useLocale();const c=(en:string,zh:string)=>pick(locale,en,zh);
 const [user,setUser]=useState(''),[tab,setTab]=useState('Products'),[products,setProducts]=useState<Product[]>([]),[leads,setLeads]=useState<Lead[]>([]),[audit,setAudit]=useState<Audit[]>([]),[home,setHome]=useState<HomeContent|null>(null);
 const [editing,setEditing]=useState<FormProduct|null>(null),[selected,setSelected]=useState<Lead|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string>>({});
 const errorRef=useRef<HTMLDivElement>(null);
 function failure(e:unknown){setError(localizeApiMessage(locale,e instanceof Error?e.message:'Please try again.'));setFields(e instanceof RequestError?e.fields:{});setTimeout(()=>errorRef.current?.focus(),0);}
 async function refresh(){const[p,l,h,a]=await Promise.all([request<Product[]>('admin/products'),request<Lead[]>('admin/leads'),request<HomeContent>('content/home'),request<Audit[]>('admin/audit')]);setProducts(p);setLeads(l);setHome(h);setAudit(a);}
 useEffect(()=>{request<{email:string}>('auth/me').then(async me=>{setUser(me.email);await refresh();}).catch(failure).finally(()=>setLoading(false));},[]);
 function selectTab(value:string){setTab(value);setEditing(null);setSelected(null);setError('');setMessage('');}
 async function saveProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError('');setFields({});
  const fd=new FormData(e.currentTarget);const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement;
  const payload={...editing,name:String(fd.get('name')),slug:String(fd.get('slug')),sku:String(fd.get('sku')),summary:String(fd.get('summary')),description:String(fd.get('description')),category:String(fd.get('category')),age_min:Number(fd.get('age_min')),age_max:Number(fd.get('age_max')),environment:String(fd.get('environment')),features:String(fd.get('features')).split('\n').map(v=>v.trim()).filter(Boolean),safety_notes:String(fd.get('safety_notes')),seo_title:String(fd.get('seo_title')),seo_description:String(fd.get('seo_description')),status:submitter?.value||'draft',specs:{} as Record<string,string>};
  for(const line of String(fd.get('specs')).split('\n').filter(v=>v.trim())){const i=line.indexOf(':');if(i<1){setBusy(false);failure(new Error(c('Write each specification as Name: value.','每条规格请使用“名称: 内容”的格式。')));return;}payload.specs[line.slice(0,i).trim()]=line.slice(i+1).trim();}
  try{const saved=await request<Product>(editing.id?`admin/products/${editing.id}`:'admin/products',payload,editing.id?'PATCH':'POST');setEditing(saved);await refresh();setMessage(saved.status==='active'?c('Product published. It is now visible on the website.','产品已发布，现在可在官网查看。'):saved.status==='archived'?c('Product archived. Its detail URL is retained.','产品已归档，详情网址仍然保留。'):c('Draft saved.','草稿已保存。'));}catch(e){failure(e);}finally{setBusy(false);}
 }
 async function upload(file?:File){if(!file||!editing)return;setBusy(true);setError('');
  try{if(file.size>2*1024*1024)throw new Error(c('Choose an image under 2 MB.','请选择小于 2 MB 的图片。'));const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const saved=await request<{id:string;alt:string}>('admin/media',{data,alt:editing.name||file.name.replace(/\.[^.]+$/,'')});setEditing({...editing,image_id:saved.id,image_alt:saved.alt});setMessage(c('Image uploaded. Save the product to attach it.','图片已上传，请保存产品以完成关联。'));}catch(e){failure(e);}finally{setBusy(false);}
 }
 async function saveLead(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const saved=await request<Lead>(`admin/leads/${selected.id}`,{status:fd.get('status'),internal_note:fd.get('internal_note'),version:selected.version},'PATCH');setSelected(saved);await refresh();setMessage(c('Inquiry updated.','咨询已更新。'));}catch(e){failure(e);}finally{setBusy(false);}}
 async function saveHome(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!home)return;setBusy(true);setError('');try{await request('admin/content/home',{...Object.fromEntries(new FormData(e.currentTarget)),version:home.version},'PATCH');await refresh();setMessage(c('Homepage content updated.','首页内容已更新。'));}catch(e){failure(e);}finally{setBusy(false);}}
 const field=(name:string,label:string,large=false)=>{const value=editing?(editing as any)[name]:'';return <label key={name}>{label}{large?<textarea id={name} name={name} rows={name==='description'?6:3} defaultValue={value} aria-describedby={`${name}-error`}/>:<input id={name} name={name} defaultValue={value} required={['name','sku','slug'].includes(name)} aria-describedby={`${name}-error`}/>}<small className="field-error" id={`${name}-error`}>{fields[name]}</small></label>;};
 const navNames:Record<string,string>={Products:c('Products','产品'),Inquiries:c('Inquiries','咨询'),Homepage:c('Homepage','首页'),Activity:c('Activity','操作记录')};
 return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="wordmark">WEMOVE<span>{c('TEAM WORKSPACE','团队工作台')}</span></Link><nav aria-label={c('Workspace','工作台')}>{['Products','Inquiries','Homepage','Activity'].map(t=><button key={t} onClick={()=>selectTab(t)} aria-current={tab===t?'page':undefined}>{navNames[t]}{t==='Inquiries'&&<span>{leads.filter(l=>l.status==='new').length}</span>}</button>)}</nav><LanguageSwitcher compact/><div className="sidebar-bottom"><Link href="/" target="_blank">{c('View website','查看网站')} ↗</Link><small>{user}</small><button onClick={async()=>{await request('auth/logout',{});window.location.href='/admin/login';}}>{c('Sign out','退出登录')}</button></div></aside>
 <main className="admin-main" id="main-content"><header className="admin-heading"><div><p className="eyebrow">{c('CONTENT & OPERATIONS','内容与运营')}</p><h1>{editing?(editing.id?c('Edit product','编辑产品'):c('New product','新建产品')):selected?selected.reference:navNames[tab]}</h1></div>{tab==='Products'&&!editing&&<button className="button" onClick={()=>{setEditing({...blank});setMessage('');setError('');}}>+ {c('New product','新建产品')}</button>}</header>
 {error&&<div ref={errorRef} className="error-summary" role="alert" tabIndex={-1}><strong>{error}</strong>{Object.entries(fields).map(([key,val])=><a href={`#${key.split('.')[0]}`} key={key}>{key}: {val}</a>)}</div>}{message&&<div className="success-message" role="status">{message}</div>}
 {loading?<p role="status">{c('Loading workspace…','正在加载工作台…')}</p>:<>
 {tab==='Products'&&!editing&&<><div className="admin-summary"><span><b>{products.length}</b>{c('Total products','产品总数')}</span><span><b>{products.filter(p=>p.status==='active').length}</b>{c('Published','已发布')}</span><span><b>{products.filter(p=>p.status==='draft').length}</b>{c('Drafts','草稿')}</span></div>{products.length?<div className="table-scroll"><table><thead><tr><th>{c('Product','产品')}</th><th>SKU</th><th>{c('Category','类别')}</th><th>{c('Status','状态')}</th><th>{c('Action','操作')}</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>/{p.slug}</small></td><td>{p.sku}</td><td>{displayCategory(locale,p.category)}</td><td><span className={`badge ${p.status}`}>{p.status==='active'?c('active','已发布'):p.status==='draft'?c('draft','草稿'):c('archived','已归档')}</span></td><td><button className="text-button" onClick={()=>{setEditing(p);setMessage('');}}>{c('Edit','编辑')} <span className="sr-only">{p.name}</span> ↗</button></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>{c('Your collection starts here.','从这里开始建立产品系列。')}</h2><p>{c('Create a draft, add real product information and an image, then publish.','先建立草稿，添加真实产品信息和图片，再进行发布。')}</p></div>}</>}
 {tab==='Products'&&editing&&<form className="editor" key={`${editing.id}:${editing.version}`} onSubmit={saveProduct}><button className="text-button" type="button" onClick={()=>setEditing(null)}>← {c('Back to products','返回产品列表')}</button><div className="editor-grid"><section><h2>{c('Product information','产品信息')}</h2><div className="form-columns">{field('name',c('Product name','产品名称'))}{field('sku','SKU')}{field('slug',c('URL slug','网址标识'))}<label>{c('Activity','活动类型')}<select name="category" defaultValue={editing.category}>{['Bowling','Balance & coordination','Outdoor games'].map(v=><option key={v} value={v}>{displayCategory(locale,v)}</option>)}</select></label></div>{field('summary',c('Short description','简短描述'),true)}{field('description',c('Description / how to play','详细描述与玩法'),true)}<label>{c('Features','产品特点')} <small>{c('One per line. Three to six are required to publish.','每行一条，发布时需要三至六条。')}</small><textarea id="features" name="features" rows={4} defaultValue={editing.features.join('\n')}/></label><div className="form-columns"><label>{c('Minimum age','最小年龄')}<input type="number" name="age_min" id="age_min" min="0" max="99" defaultValue={editing.age_min}/></label><label>{c('Maximum age','最大年龄')}<input type="number" name="age_max" id="age_max" min="0" max="99" defaultValue={editing.age_max}/></label><label>{c('Play space','使用空间')}<select name="environment" defaultValue={editing.environment}>{['indoor','outdoor','both'].map(v=><option key={v} value={v}>{displayEnvironment(locale,v)}</option>)}</select></label></div><label>{c('Specifications','规格')} <small>{c('One per line, for example Material: wood. Enter verified details only.','每行一条，例如“材质: 木材”。只填写已经核实的信息。')}</small><textarea name="specs" rows={4} defaultValue={Object.entries(editing.specs).map(([k,v])=>`${k}: ${v}`).join('\n')}/></label>{field('safety_notes',c('Safety & care','安全与保养'),true)}</section>
 <section><h2>{c('Main image','主图')}</h2><div className="upload-box" id="image_id">{editing.image_id?<img src={`/api/media/${editing.image_id}`} alt={editing.image_alt||c('Product preview','产品预览')} width="320" height="320"/>:<p>{c('Upload a real product image.','上传真实产品图片。')}</p>}<label>{c('Choose image','选择图片')}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label><small>PNG, JPEG or WebP · {c('up to 2 MB','最大 2 MB')}</small><small className="field-error">{fields.image_id}</small></div><h2>{c('Search appearance','搜索展示')}</h2>{field('seo_title',c('SEO title','SEO 标题'))}{field('seo_description',c('SEO description','SEO 描述'),true)}<p className="notice">{c('Drafts stay private. Published products appear immediately. Archived products keep their detail URL.','草稿保持私有，发布后立即出现在官网，归档产品仍保留详情网址。')}</p></section></div><div className="editor-actions"><button className="button secondary" value="draft" disabled={busy}>{busy?c('Saving…','正在保存…'):c('Save draft','保存草稿')}</button><button className="button" value="active" disabled={busy}>{c('Publish product','发布产品')}</button>{editing.id&&<button className="text-button danger" value="archived" disabled={busy}>{c('Archive','归档')}</button>}</div></form>}
 {tab==='Inquiries'&&!selected&&(leads.length?<div className="table-scroll"><table><thead><tr><th>{c('Reference / subject','编号与主题')}</th><th>{c('Contact','联系人')}</th><th>{c('Type','类型')}</th><th>{c('Status','状态')}</th><th>{c('Action','操作')}</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><strong>{l.subject}</strong><small>{l.reference}</small></td><td>{l.name}<small>{l.email}</small></td><td>{l.type}</td><td><span className="badge">{l.status==='new'?c('New','新建'):l.status==='in_progress'?c('In progress','处理中'):c('Resolved','已解决')}</span></td><td><button className="text-button" onClick={()=>{setSelected(l);setMessage('');}}>{c('Open','打开')} ↗</button></td></tr>)}</tbody></table></div>:<div className="empty-state"><h2>{c('No inquiries yet.','暂无咨询。')}</h2><p>{c('Messages submitted through the contact page will appear here.','联系页面提交的消息会显示在这里。')}</p><Link href="/contact" className="text-link">{c('Open contact page','打开联系页面')} ↗</Link></div>)}
 {tab==='Inquiries'&&selected&&<div className="editor"><button className="text-button" onClick={()=>setSelected(null)}>← {c('All inquiries','全部咨询')}</button><div className="editor-grid"><section><p className="eyebrow">{selected.type}</p><h2>{selected.subject}</h2><p>{selected.name} · {selected.email} · {selected.country}</p><p className="preserve-text inquiry-message">{selected.message}</p></section><form onSubmit={saveLead} key={selected.version}><label>{c('Status','状态')}<select name="status" defaultValue={selected.status}><option value="new">{c('New','新建')}</option><option value="in_progress">{c('In progress','处理中')}</option><option value="resolved">{c('Resolved','已解决')}</option></select></label><label>{c('Internal note','内部备注')}<textarea name="internal_note" rows={7} maxLength={4000} defaultValue={selected.internal_note}/><small>{c('Only visible in this workspace. Saving does not send an email.','仅在工作台中可见，保存不会发送邮件。')}</small></label><button className="button" disabled={busy}>{busy?c('Saving…','正在保存…'):c('Save changes','保存修改')}</button></form></div></div>}
 {tab==='Homepage'&&home&&<form className="editor home-editor" key={home.version} onSubmit={saveHome}><h2>{c('Brand introduction','品牌介绍')}</h2><p>{c('Update the live homepage and Our story page.','更新官网首页和品牌故事页面。录入内容按原语言在两种界面中展示。')}</p>{Object.entries({hero_title:c('Hero title','首屏标题'),hero_subtitle:c('Hero subtitle','首屏副标题'),cta_label:c('Product button label','产品按钮文字'),about:c('Brand introduction','品牌介绍')}).map(([name,label])=><label key={name}>{label}{name==='about'?<textarea name={name} rows={8} defaultValue={(home.data as any)[name]} required/>:<input name={name} defaultValue={(home.data as any)[name]} required/>}</label>)}<button className="button" disabled={busy}>{busy?c('Saving…','正在保存…'):c('Save website content','保存网站内容')}</button></form>}
 {tab==='Activity'&&<div className="table-scroll"><table><thead><tr><th>{c('Action','操作')}</th><th>{c('Object','对象')}</th><th>{c('Team member','团队成员')}</th><th>{c('Time','时间')}</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{a.action}</td><td>{a.entity}<small>{a.entity_id}</small></td><td>{a.email||c('System','系统')}</td><td>{new Date(a.created_at).toLocaleString(locale==='zh'?'zh-CN':'en-US')}</td></tr>)}</tbody></table></div>}
 </> }</main></div>;
}
